# Generated by Django 2.0.1 on 2018-01-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_generator', '0003_auto_20180128_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=1000)),
                ('sub_item_groups', models.ManyToManyField(blank=True, to='offer_generator.ItemGroup')),
                ('sub_items', models.ManyToManyField(blank=True, to='offer_generator.Item')),
            ],
        ),
    ]
